/**
 * ==================================================
 * Copyright (C) 2024 wemove digital solutions GmbH
 * ==================================================
 * Licensed under the EUPL, Version 1.2 or - as soon they will be
 * approved by the European Commission - subsequent versions of the
 * EUPL (the "Licence");
 *
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 *
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and
 * limitations under the Licence.
 * ==================================================
 */

import autoload from '@fastify/autoload';
import swagger from '@fastify/swagger';
import ScalarApiReference from '@scalar/fastify-api-reference';
import Fastify from 'fastify';
import path from 'path';
import config from './config.js';
import logger from './utils/logger.js';

const BASE_URL = '/' + (config.server.baseUrl?.trim().replace(/^\/*|\/*$/g, '').trim() ?? '');
const API_DOCS_URL = 'api-docs';

export default async function app() {

    const server = Fastify({
        loggerInstance: logger,
        ignoreTrailingSlash: true
    });

    let version = 'v1';
    const VERSION_BASE_URL = `${BASE_URL}/${version}`.trim().replace(/\/+/g, '/').trim();

    // configure swagger
    const swaggerConfig = {
        openapi: {
            openapi: '3.0.3',
            info: {
                title: 'Geodata Conversion API',
                description: 'This API converts geometry information from and to various formats. Additionally, it can create centroid and bbox information.',
                version: config.server.build.version
            },
            servers: [{ url: VERSION_BASE_URL }]
        }
    }
    await server.register(swagger, swaggerConfig);

    server.setErrorHandler((error, request, reply) => {
        let message: string = "Internal Server Error";
        let statusCode = 500;
        if (typeof error === 'string') {
            message = error;
        }
        else if (error instanceof Error) {
            message = error.message;
            if ('cause' in error && typeof(error.cause) === 'number') {
                statusCode = error.cause;
            }
            else if ('statusCode' in error && typeof(error.statusCode) === 'number') {
                statusCode = error.statusCode;
            }
        }
        return reply.header('Content-Type', 'text/plain').status(statusCode).send(message);
    });

    // register routes
    const routesBaseDir = path.resolve(import.meta.dirname, `api/${version}/routes`);
    await server.register(autoload, {
        dir: routesBaseDir,
        forceESM: true,
        indexPattern: /^index\.(js|ts)$/,
        maxDepth: 1,
        routeParams: true,
        options: { prefix: VERSION_BASE_URL },
        dirNameRoutePrefix: (folderParent: string, folderName: string) => {
            return `/${folderName}`;
        }
    });

    // route for api documentation generated by scalar
    const apiDocsUrl = `${VERSION_BASE_URL}/${API_DOCS_URL}`;
    await server.register(ScalarApiReference, {
        routePrefix: apiDocsUrl,
        configuration: {
            spec: () => server.swagger(),
        },
    });

    return server;
}
