/**
 * ==================================================
 * geo-conversion-api
 * ==================================================
 * Copyright (C) 2024 wemove digital solutions GmbH
 * ==================================================
 * Licensed under the EUPL, Version 1.2 or - as soon they will be
 * approved by the European Commission - subsequent versions of the
 * EUPL (the "Licence");
 * 
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 * 
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and
 * limitations under the Licence.
 * ==================================================
 */

import autoload from '@fastify/autoload';
import swagger from '@fastify/swagger';
import ScalarApiReference from '@scalar/fastify-api-reference';
import Fastify from 'fastify';
import path from 'path';
import config from './config.js';
import { parseNumber } from './utils/utils.js';

const server = Fastify({
    logger: true,
    ignoreTrailingSlash: true
});

const BASE_URL = '/' + (config.server.baseUrl?.trim().replace(/^\/*|\/*$/g, '').trim() ?? '');

const API_DOCS_URL = 'api-docs';

// Run the server!
async function start() {

    let version = 'v1';
    const versionBaseUrl = `${BASE_URL}/${version}`.trim().replace(/\/+/g, '/').trim();

    // configure swagger
    const swaggerConfig = {
        openapi: {
            openapi: '3.0.3',
            info: {
                title: 'Geodata Conversion API',
                description: 'This is a REST API for the conversion of geodata',
                version: '0.1.0'
            },
            servers: [{ url: versionBaseUrl }],
            tags: [{
                name: 'Convert',
                description: 'Endpoints for getting information about the API'
            }, {
                name: 'Info',
                description: 'Endpoints for getting information about the API'
            }]
        }
    }
    await server.register(swagger, swaggerConfig)

    // register routes
    const routesBaseDir = path.resolve(import.meta.dirname, `api/${version}/routes`);
    await server.register(autoload, {
        dir: routesBaseDir,
        forceESM: true,
        indexPattern: /^.*index\.ts$/,
        maxDepth: 1,
        routeParams: true,
        options: { prefix: versionBaseUrl },
        dirNameRoutePrefix: (folderParent: string, folderName: string) => {
            return `/${folderName}`;
        }
    });

    // route for api documentation generated by scalar
    const apiDocsUrl = `${versionBaseUrl}/${API_DOCS_URL}`;
    await server.register(ScalarApiReference, {
        routePrefix: apiDocsUrl,
        configuration: {
            spec: () => server.swagger(),
        },
    });

    try {
        let port = parseNumber(process.env.GEO_API_PORT) ?? 3000;
        await server.listen({ host: '0.0.0.0', port });
    }
    catch (err) {
        server.log.error(err);
        process.exit(1);
    }
}

start();
